const h1 = document.createElement("h1");
const body = document.getElementsByTagName("body")[0];
const p1 = document.createElement("p1");
const div = document.createElement("div");
const p2 = document.createElement("p2");
const img = document.createElement("img");
const div2 = document.createElement("div2");
div2.className = "sondiv";
div.className = "fatherdiv";
img.src = "car.jpeg";
img.className = "photo";
h1.innerText = "3 сая төгрөг";
h1.className = "title";
p1.innerText = "Nissan presage";
p1.className = "ptag";
p2.innerText = "190000km Avtomat 2.4l benzin 16 minutiin umnu";
p2.className = "p2tag";
body.appendChild(div);
div.appendChild(div2);
div2.appendChild(img);
div.appendChild(h1);
div.appendChild(p1);
div.appendChild(p2);
